# Generated by Django 3.1.4 on 2020-12-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCommandStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('uid', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('description', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='GuildCommandStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('guild_id', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='GuildSubCommandStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=180, unique=True)),
                ('username', models.CharField(max_length=180)),
                ('avatar', models.CharField(max_length=180)),
                ('discriminator', models.IntegerField()),
                ('public_flags', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=180)),
                ('extra_data', models.TextField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSubCommandStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('uid', models.CharField(max_length=180)),
                ('options', models.TextField()),
                ('master_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord_interactions.globalcommandstorage')),
            ],
        ),
    ]
